### ISSUE TITLE
Wrong date order

### ISSUE THREAD

**Issue by Mayaryin** [emilyCheroske/GoalStreak#10]
**Describe the bug**
When week is set to start with Monday (default is Sunday), the date is falsely appended to the end of the days list, essentially "jumping back in time"

**To Reproduce**
1. Go to settings
2. Click on 'start of week'
3. choose 'Monday'
4. See error in calendar view 

**Expected behavior**
The dates should appear like this:
Mon, 30th
Tue, 31st
Wed, 1st
Thu, 2nd
Fri, 3rd
Sat, 4th
Sun, 5th

Instead 'Sun, 29th' is displayed

**Screenshots**

![image](https://github.com/user-attachments/assets/a4108aaf-7c42-4e42-b5db-8a64c0ff97a2)

**Device and app info:**
 - Device: iPhoneXS
 - OS: iOS8.1
 - Version 52

**Comment by emilyCheroske** [comment]
Hey there! This should be fixed in version 2025.01.0 which is available on the App Store now!

**Comment by Mayaryin** [comment]
Great, works now. Thank you for this super quick fix and keep up the cool work :)
