### ISSUE TITLE
Can you make an option that weeks star with Monday and kot Sunday?  Thank you

### ISSUE THREAD

**Issue by jakobzeise** [emilyCheroske/GoalStreak#6]

**Comment by emilyCheroske** [comment]
Hey! This will be coming out in the next release - you will be able to set the start of your week to any day you like in settings. I'll comment and close this issue out once it's available for download in the App Store 🤗

**Comment by emilyCheroske** [comment]
This is now available in version 2025.01.0 which is on the App Store now!

**Comment by jakobzeise** [comment]
Thank you :)
