### ISSUE TITLE
Calendar incorrect

### ISSUE THREAD

**Issue by mrybinski14** [emilyCheroske/GoalStreak#9]
**Describe the bug**
The horizontal scrolling calendar at the top of the task list is not correct. Today is the 29th, but the horizontal scrolling calendar actually skips the 29th and 30th, and says today is the 31st. When I click on “December 2024” to get the full calendar view, it is correctly showing today as the 29th (Sunday).

**To Reproduce**
1. Go to the main page
2. View the horizontal scrolling calendar at the top of the page, above the task list
3. See error
4. Compare to full calendar view by clicking “December 2024”

**Expected behavior**
This is truly a tiny fix (hopefully)! Just saw an inconsistency with dates.

**Screenshots**
![IMG_3695](https://github.com/user-attachments/assets/d3c143e5-615e-4d36-9be1-bdd11dcff687)

**Please complete the following information:**
 - Device: iPhone 13
 - OS: iOS 18.1
 - Version 2024.50.1

**Comment by emilyCheroske** [comment]
@mrybinski14 Sorry you ran into this! I just shipped out an update to the App Store hopefully they review and approve it soon🤞

**Comment by emilyCheroske** [comment]
This should be fixed in version 2025.01.0!
